name: Scrap

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    timeout-minutes: 60

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Ensure Gradle is executable
        working-directory: ./Scrapping
        run: chmod +x gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run Scrapping
        working-directory: ./Scrapping
        run: ./gradlew run --stacktrace --no-daemon --info

      - name: Move files
        working-directory: ./Scrapping
        run: mv ./output/* ../Api

      - name: Commit and push changes
        continue-on-error: true
        run: |
          git config --global user.name "XibalbaM"
          git config --global user.email "xibalbam@users.noreply.github.com"
          git add .
          git commit -m "Update data"
          git push